
testthat::test_that("Bookdown renders without error.", {
  withr::local_options(
    rlang_interactive = FALSE
  )
  withr::local_package("testthat")
  withr::local_package("rsconnect")
  withr::local_package("bookdown")
  withr::local_package("rmarkdown")
  withr::local_package("plotly")
  withr::local_package("shiny")
  withr::local_package("tidycensus")
  withr::local_package("tidyverse")
  withr::local_package("viridis")
  withr::local_package("ggmap")
  withr::local_package("ggplot2")
  withr::local_package("maps")
  withr::local_package("dplyr")
  withr::local_package("knitr")
  withr::local_package("latticeExtra")
  withr::local_package("pals")
  withr::local_package("classInt")
  withr::local_package("sf")
  withr::local_package("udunits2")
  withr::local_package("tmap")
  withr::local_package("lubridate")
  withr::local_package("gifski")
  withr::local_package("magick")
  expect_no_error(
    bookdown::render_book("../")
  )
})
