# **A3** PEGS Data Dictionary {.unnumbered}

*[Page Note:  add links to catalog for sources, add links to tools for tools]*

The following table provides a list of geospatial-based exposure measures used in
the NIEHS Personalized Environment and Genes Study, including their sources and links
to tools to use to compute these measures.  

The sources include:

* TRI = EPA Toxic Release Inventory
* ACAG = Atmospheric Composition Analysis Group
* CACES = Center for Air, Climate, & Energy Solutions 
* FAA = Federal Aviation Administration
* NCDEQ = North Carolina Department of Environmental Quality
* FCC = Federal Communications Commission
* NRC = Nuclear Regulatory Commission
* DOT = Department of Transportation
* EJI = Environmental Justice Index
* Merra2 = NASA Global Modeling and Assimilation Office


|variable_name     |description      | variable_source  |  
|-------|------------------------------|----------------|  
|gis_latitude  |Latitude coordinate   |Geocoding of subject data   |  
|hazards_pm25_ammonium_ugm3  |ACAG estimated PM2.5 conponent: ammonium ion concentration (micrograms per cubic meter)   |ACAG   |  
|hazards_benzene_1km  |Estimated xylene mass in kg using an isotropic sum of exponentially decaying mass equation with an exponential decay range of 1km (see Eq 1).   |TRI   |  
