# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? 
# Start at https://github.com/r-lib/actions#where-to-find-help
---
name: Check Render Bookdown

on:
  pull_request:

jobs:
  check_render:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install libudunits2 and libmagick
        run: |
          sudo apt-get install -y libudunits2-dev libgdal-dev
          sudo apt-get install libmagick++-dev

      - name: Install pandoc-citeproc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc-citeproc

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::testthat
            any::bookdown
            any::covr

      - name: Render Bookdown
        run: |
          install.packages(c(
            "testthat",
            "rsconnect",
            "bookdown",
            "rmarkdown",
            "plotly",
            "shiny",
            "tidycensus",
            "tidyverse",
            "viridis",
            "ggmap",
            "ggplot2",
            "maps",
            "dplyr",
            "knitr",
            "latticeExtra",
            "pals",
            "classInt",
            "sf",
            "udunits2",
            "tmap",
            "lubridate",
            "gifski",
            "magick",
            "cowplot",
            "BiocManager"
            ),
            dependencies = TRUE
          )
          BiocManager::install("Biobase")
          covr::environment_coverage(
            test_files = "tests/test-render_bookdown.R"
          )
        shell: Rscript {0}
