# # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# # Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# ---
# name: Deploy Toolkit

# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
#   release:
#     types: [published]
#   workflow_dispatch:
  
# jobs:
#   deploy_toolkit:
#     runs-on: ubuntu-latest

#     # Only restrict concurrency for non-PR jobs
#     concurrency:
#       group: bookdown-${{ github.event_name != 'pull_request' || github.run_id }}

#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

#     permissions:
#       contents: write

#     steps:
#       - uses: actions/checkout@v4

#       - uses: r-lib/actions/setup-pandoc@v2

#       - uses: r-lib/actions/setup-r@v2
#         with:
#           use-public-rspm: true

#       - name: Install libudunits2 and libmagick
#         run: |
#           sudo apt-get install -y libudunits2-dev libgdal-dev
#           sudo apt-get install libmagick++-dev

#       - name: Build site
#         run: |
#           install.packages(c(
#             "bookdown",
#             "rmarkdown",
#             "plotly",
#             "shiny",
#             "tidycensus",
#             "tidyverse",
#             "viridis",
#             "ggmap",
#             "ggplot2",
#             "maps",
#             "dplyr",
#             "knitr",
#             "latticeExtra",
#             "pals",
#             "classInt",
#             "sf",
#             "udunits2",
#             "tmap",
#             "lubridate",
#             "gifski",
#             "magick",
#             "cowplot",
#             "BiocManager"
#             ),
#             dependencies = TRUE
#           )
#           BiocManager::install("Biobase")
#           bookdown::render_book()
#         shell: Rscript {0}

#       - name: Deploy to GitHub pages 🚀
#         if: github.event_name != 'pull_request'
#         uses: JamesIves/github-pages-deploy-action@v4.4.1
#         with:
#           clean: false
#           branch: gh-pages
#           folder: docs