---
name: Protect Branch `staging-public`

on:
  pull_request:

jobs:
  protect_staging_1:
    name: Protect Branch `staging-public`
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.base.ref == 'staging-public'

    steps:
      - name: Check Source Branch
        run: |
          source_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          if [[ "$source_branch" != "staging-internal" ]]; then
            echo "Pull requests into 'staging-public' must come from 'staging-internal'."
            exit 1
          fi
