---
name: Protect Branch `main`

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  delete_staging_1_on_merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Source Branch
        if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master'
        run: |
          source_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          if [[ "$source_branch" != "staging-1" ]]; then
            echo "Pull requests into 'main' must come from 'staging-1'."
            exit 1
          fi
