---
name: Protect Branch `staging-public`

on:
  pull_request:

jobs:
  protect_staging_public:
    name: Protect Branch `staging-public`
    runs-on: ubuntu-latest

    steps:
      - name: Check base branch
        id: check-base-branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "staging-public" ]]; then
            echo "Protected branch \"staging-public\" detected in pull request."
            echo "continue=true" >> "$GITHUB_OUTPUT"
           else
            echo "Protected branch \"staging-public\" not detected in pull request."
            echo "continue=false" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Check source branch
        run: |
          continue="${{ steps.check-base-branch.outputs.continue }}"
          if [[ "$continue" == "true" ]]; then
            source_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
            if [[ "$source_branch" != "staging-internal" ]]; then
              echo "Pull requests into \"staging-public\" must come from \"staging-internal\"."
              exit 1
            fi
          else
            echo "Protected branch \"staging-public\" not detected in pull request."
          fi
