---
name: Protect Branch `main`

on:
  pull_request:

jobs:
  protect_main:
    name: Protect Branch `main`
    runs-on: ubuntu-latest

    steps:
      - name: Check base branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" || "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            echo "Protected branch 'main' detected in pull request."
          else
            echo "Protected branch 'main' not detected in pull request."
            return 0
          fi
      
      - name: Check source branch
        run: |
          source_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          if [[ "$source_branch" != "staging-public" ]]; then
            echo "Pull requests into 'main' must come from 'staging-public'."
            exit 1
          fi
