---
name: Super Linter

on:
  push:
  pull_request:

jobs:
  super-lint:
    name: Lint all file types
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: .*/doc/*
          LINTR_ERROR_ON_LINT: true
