# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
---
name: Render bookdown

on:
  push:
  pull_request:

jobs:
  test-render-bookdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev
      
      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Install dependencies for testthat
        run: |
          R -e 'install.packages(c("testthat", "bookdown"), dependencies = TRUE)'

      - name: Run tests
        run: |
          R -e 'library(testthat); testthat::test_file(path = "tests/test-bookdown_render.R")'

      - name: Cleanup
        run: |
          R -e 'remove.packages("remotes")'